table:
    path:     /
    defaults: { _controller: "AppBundle:ExtGramfoodkompow:index" }

table_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ExtGramfoodkompow:show" }

table_new:
    path:     /new
    defaults: { _controller: "AppBundle:ExtGramfoodkompow:new" }

table_create:
    path:     /create
    defaults: { _controller: "AppBundle:ExtGramfoodkompow:create" }
    requirements: { _method: post }

table_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ExtGramfoodkompow:edit" }

table_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:ExtGramfoodkompow:update" }
    requirements: { _method: post|put }

table_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ExtGramfoodkompow:delete" }
    requirements: { _method: post|delete }
